DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGVtYWlsLmNvbSIsImV4cCI6MTc0ODI4NTMxOCwidXNlcklkIjoyfQ.3xLeuLKbjkGrZg8Gf543bZ11pLR8kaDFLK6_8ms2t2U
